import React, { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import {
  Sparkles, Map, DollarSign, Users, Share2, Shield,
  ChevronRight, Globe, Zap, ArrowRight
} from 'lucide-react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { popularDestinations } from '../data/mockData';
import { StaggerContainer, StaggerItem, FloatingOrb } from '../components/ui/motion';

// â”€â”€â”€ Animated Counter â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// (removed â€” stats section deleted per user request)

// â”€â”€â”€ Features â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const features = [
  { icon: Sparkles,  color: '#0ea5e9', bg: '#e0f2fe', title: 'AI Itinerary Generator',  desc: 'Get a personalized day-by-day itinerary generated by AI based on your travel style, budget, and preferences.' },
  { icon: DollarSign,color: '#f97316', bg: '#fff7ed', title: 'Smart Budget Tracker',    desc: 'Track every expense, set category budgets, and get alerts before you overspend.' },
  { icon: Map,       color: '#14b8a6', bg: '#f0fdfa', title: 'Interactive Map View',    desc: 'Visualize your entire trip on a map. Discover nearby attractions and hidden gems.' },
  { icon: Users,     color: '#8b5cf6', bg: '#f5f3ff', title: 'Group Collaboration',     desc: 'Plan trips with friends and family in real time. Assign tasks and stay in sync.' },
  { icon: Share2,    color: '#ec4899', bg: '#fdf2f8', title: 'Easy Trip Sharing',       desc: 'Share your trip publicly or invite specific people. Full access control.' },
  { icon: Shield,    color: '#22c55e', bg: '#f0fdf4', title: 'Secure & Private',        desc: 'Your travel data is encrypted and protected. Choose what to share.' },
];

// â”€â”€â”€ How It Works â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const steps = [
  { n: '01', title: 'Tell us your dream',     desc: 'Share your destination, dates, budget, and travel style.' },
  { n: '02', title: 'AI builds your trip',    desc: 'Our AI generates a personalized day-by-day itinerary.' },
  { n: '03', title: 'Customize & collaborate',desc: 'Edit activities and invite your travel companions.' },
  { n: '04', title: 'Travel & track',         desc: 'Follow your itinerary and track spending on the go.' },
];

// â”€â”€â”€ Hero Section â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const Hero: React.FC = () => {
  const cardRef = useRef<HTMLDivElement>(null);

  // Subtle 3D tilt on mouse move
  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!cardRef.current) return;
    const rect = cardRef.current.getBoundingClientRect();
    const x = (e.clientX - rect.left) / rect.width  - 0.5;
    const y = (e.clientY - rect.top)  / rect.height - 0.5;
    cardRef.current.style.transform =
      `perspective(1000px) rotateY(${x * 12}deg) rotateX(${-y * 10}deg) translateZ(10px)`;
  };
  const handleMouseLeave = () => {
    if (!cardRef.current) return;
    cardRef.current.style.transform =
      `perspective(1000px) rotateY(0deg) rotateX(0deg) translateZ(0px)`;
  };

  return (
    <section className="relative min-h-screen flex items-center overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 noise" style={{
        background: 'linear-gradient(135deg, #060e1a 0%, #0f2035 45%, #1e3a5f 75%, #0c4a6e 100%)'
      }} />

      {/* Animated orbs */}
      <FloatingOrb color="radial-gradient(circle, #0ea5e9, transparent)" size={500} x="60%" y="-10%" delay={0} opacity={0.12} />
      <FloatingOrb color="radial-gradient(circle, #f97316, transparent)" size={350} x="-5%"  y="55%"  delay={2} opacity={0.10} />
      <FloatingOrb color="radial-gradient(circle, #8b5cf6, transparent)" size={250} x="75%"  y="70%"  delay={4} opacity={0.08} />

      {/* Grid pattern */}
      <div className="absolute inset-0 opacity-[0.04]" style={{
        backgroundImage: 'linear-gradient(rgba(255,255,255,.5) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.5) 1px, transparent 1px)',
        backgroundSize: '48px 48px',
      }} />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-20 w-full">
        <div className="grid lg:grid-cols-2 gap-16 items-center">

          {/* Left â€” copy */}
          <div>
            <motion.div
              initial={{ opacity: 0, y: -12 }}
              animate={{ opacity: 1, y:   0  }}
              transition={{ duration: 0.6 }}
              className="inline-flex items-center gap-2 px-4 py-2 mb-7 rounded-full text-white/90 text-sm font-semibold border border-white/20 glass"
            >
              <Sparkles className="w-4 h-4 text-[#f97316]" />
              AI-Powered Travel Planning
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 28 }}
              animate={{ opacity: 1, y: 0  }}
              transition={{ duration: 0.7, delay: 0.08 }}
              className="text-5xl lg:text-6xl xl:text-7xl font-bold font-display text-white leading-[1.08] mb-6"
            >
              Plan Your Dream
              <span className="block mt-1"
                style={{
                  background: 'linear-gradient(135deg, #f97316 0%, #fbbf24 50%, #f97316 100%)',
                  backgroundSize: '200%',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  backgroundClip: 'text',
                  animation: 'gradientShift 4s ease infinite',
                }}>
                Trip in Minutes
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y:  0 }}
              transition={{ duration: 0.6, delay: 0.18 }}
              className="text-white/70 text-lg leading-relaxed mb-10 max-w-lg"
            >
              TripNest uses AI to create personalized itineraries, track your budget,
              discover amazing places, and collaborate with your travel companions â€”
              all in one beautiful platform.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y:  0 }}
              transition={{ duration: 0.5, delay: 0.28 }}
              className="flex flex-wrap gap-4"
            >
              <motion.div whileHover={{ scale: 1.03, y: -2 }} whileTap={{ scale: 0.97 }}>
                <Link
                  to="/signup"
                  className="flex items-center gap-2 px-7 py-3.5 bg-[#f97316] text-white font-bold rounded-xl hover:bg-[#ea580c] transition-all shadow-lg text-base glow-orange"
                >
                  Start Planning Free <ArrowRight className="w-5 h-5" />
                </Link>
              </motion.div>
              <motion.div whileHover={{ scale: 1.03, y: -2 }} whileTap={{ scale: 0.97 }}>
                <Link
                  to="/login"
                  className="flex items-center gap-2 px-7 py-3.5 glass text-white font-bold rounded-xl border border-white/30 hover:bg-white/20 transition-all text-base"
                >
                  See Demo
                </Link>
              </motion.div>
            </motion.div>
          </div>

          {/* Right â€” 3D tilt preview card */}
          <motion.div
            className="hidden lg:block"
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x:  0 }}
            transition={{ duration: 0.8, delay: 0.15, ease: [0.4, 0, 0.2, 1] }}
          >
            <div
              ref={cardRef}
              onMouseMove={handleMouseMove}
              onMouseLeave={handleMouseLeave}
              className="relative cursor-pointer"
              style={{ transition: 'transform 0.3s ease', willChange: 'transform' }}
            >
              {/* Glow behind card */}
              <div className="absolute inset-0 rounded-3xl opacity-30 blur-2xl"
                style={{ background: 'linear-gradient(135deg, #0ea5e9, #8b5cf6)', transform: 'scale(0.85)' }} />

              {/* Main card */}
              <div className="relative bg-white rounded-3xl shadow-2xl overflow-hidden border border-white/10">
                <img
                  src="https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600"
                  alt="Paris"
                  className="w-full h-52 object-cover"
                />
                <div className="p-5">
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <h3 className="font-bold text-gray-900 text-lg">Romantic Paris Getaway</h3>
                      <p className="text-sm text-gray-500 flex items-center gap-1 mt-0.5">
                        <Globe className="w-3.5 h-3.5" /> Paris, France
                      </p>
                    </div>
                    <span className="px-2.5 py-1 bg-teal-100 text-teal-700 rounded-full text-xs font-bold">Upcoming</span>
                  </div>
                  <div className="grid grid-cols-3 gap-3 text-center mb-4">
                    {[['7', 'Days'], ['2', 'People'], ['$5K', 'Budget']].map(([v, l]) => (
                      <div key={l} className="bg-gray-50 rounded-xl py-2.5">
                        <p className="font-bold text-gray-900 text-sm">{v}</p>
                        <p className="text-gray-400 text-xs">{l}</p>
                      </div>
                    ))}
                  </div>
                  <div className="flex items-center gap-2 p-3 bg-blue-50 rounded-xl">
                    <Sparkles className="w-4 h-4 text-blue-500 flex-shrink-0" />
                    <span className="text-xs text-blue-700 font-semibold">AI generated 14-activity itinerary</span>
                  </div>
                </div>
              </div>

              {/* Floating badge â€” AI Powered */}
              <motion.div
                animate={{ y: [0, -6, 0] }}
                transition={{ duration: 3.5, repeat: Infinity, ease: 'easeInOut' }}
                className="absolute -top-4 -right-4 bg-[#f97316] text-white px-3.5 py-2 rounded-2xl shadow-xl text-sm font-bold flex items-center gap-1.5"
              >
                <Zap className="w-4 h-4" /> AI Powered
              </motion.div>

              {/* Floating badge â€” collaborators */}
              <motion.div
                animate={{ y: [0, 6, 0] }}
                transition={{ duration: 4, delay: 1, repeat: Infinity, ease: 'easeInOut' }}
                className="absolute -bottom-4 -left-4 bg-white px-4 py-3 rounded-2xl shadow-xl text-sm font-semibold text-gray-800 flex items-center gap-2 border border-gray-100"
              >
                <div className="flex -space-x-2">
                  {['sarah', 'mike', 'emma'].map(s => (
                    <img key={s} src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${s}`}
                      alt={s} className="w-7 h-7 rounded-full border-2 border-white" />
                  ))}
                </div>
                3 collaborators
              </motion.div>
            </div>
          </motion.div>
        </div>
      </div>

      {/* Wave divider */}
      <div className="absolute bottom-0 left-0 right-0">
        <svg viewBox="0 0 1440 80" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M0 80L1440 80L1440 40C1200 80 960 0 720 40C480 80 240 0 0 40L0 80Z" fill="white" className="dark:fill-[#060e1a]" />
        </svg>
      </div>
    </section>
  );
};

// â”€â”€â”€ Features Section â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const FeaturesSection: React.FC = () => (
  <section id="features" className="py-24 bg-white dark:bg-[#060e1a]">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6 }}
        className="text-center mb-16"
      >
        <span className="section-label bg-blue-50 dark:bg-blue-500/10 text-blue-600 dark:text-blue-400 mb-4">Features</span>
        <h2 className="text-4xl font-bold font-display text-gray-900 dark:text-white mb-4 mt-3">
          Everything you need to travel smarter
        </h2>
        <p className="text-gray-500 dark:text-gray-400 text-lg max-w-2xl mx-auto">
          From AI planning to real-time collaboration, TripNest handles every aspect of your travel experience.
        </p>
      </motion.div>

      <StaggerContainer className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6" delay={0.05}>
        {features.map(({ icon: Icon, color, bg, title, desc }) => (
          <StaggerItem key={title}>
            <motion.div
              whileHover={{ y: -6, transition: { duration: 0.2 } }}
              className="card-premium p-7 h-full group"
            >
              <div className="w-13 h-13 rounded-2xl flex items-center justify-center mb-5 transition-transform duration-300 group-hover:scale-110"
                style={{ backgroundColor: bg, width: 52, height: 52 }}>
                <Icon className="w-6 h-6" style={{ color }} />
              </div>
              <h3 className="font-bold text-gray-900 dark:text-white text-lg mb-2">{title}</h3>
              <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed">{desc}</p>
            </motion.div>
          </StaggerItem>
        ))}
      </StaggerContainer>
    </div>
  </section>
);

// â”€â”€â”€ Destinations Section â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const DestinationsSection: React.FC = () => (
  <section className="py-24 bg-gray-50 dark:bg-[#080f1e]">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="flex items-end justify-between mb-12">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <span className="section-label bg-orange-50 dark:bg-orange-500/10 text-orange-600 dark:text-orange-400 mb-3">Popular</span>
          <h2 className="text-4xl font-bold font-display text-gray-900 dark:text-white mt-3">Top Destinations</h2>
          <p className="text-gray-500 dark:text-gray-400 mt-1.5">Where are travelers going this season?</p>
        </motion.div>
        <Link to="/signup" className="hidden sm:flex items-center gap-1.5 text-sm font-semibold text-[#1e3a5f] dark:text-sky-400 hover:text-[#0ea5e9] transition-colors">
          Explore all <ChevronRight className="w-4 h-4" />
        </Link>
      </div>

      <StaggerContainer className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6" delay={0.05}>
        {popularDestinations.map(dest => (
          <StaggerItem key={dest.name}>
            <Link to="/signup">
              <motion.div
                whileHover={{ y: -8, transition: { duration: 0.25 } }}
                className="group relative rounded-2xl overflow-hidden h-60 shadow-lg cursor-pointer"
              >
                <img
                  src={dest.image}
                  alt={dest.name}
                  className="w-full h-full object-cover trip-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-transparent" />
                {/* Shimmer on hover */}
                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 -skew-x-12 translate-x-[-200%] group-hover:translate-x-[200%]"
                  style={{ transition: 'transform 0.7s ease, opacity 0.3s ease' }} />
                <div className="absolute bottom-4 left-4 right-4">
                  <h3 className="text-white font-bold text-xl">{dest.name}</h3>
                  <p className="text-white/60 text-sm mt-0.5">{dest.trips} trips planned</p>
                </div>
              </motion.div>
            </Link>
          </StaggerItem>
        ))}
      </StaggerContainer>
    </div>
  </section>
);

// â”€â”€â”€ How It Works â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const HowItWorks: React.FC = () => (
  <section className="py-24 bg-white dark:bg-[#060e1a]">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6 }}
        className="text-center mb-16"
      >
        <span className="section-label bg-teal-50 dark:bg-teal-500/10 text-teal-600 dark:text-teal-400 mb-3">How It Works</span>
        <h2 className="text-4xl font-bold font-display text-gray-900 dark:text-white mb-4 mt-3">
          Plan your trip in 4 easy steps
        </h2>
        <p className="text-gray-500 dark:text-gray-400 text-lg max-w-xl mx-auto">
          From idea to adventure â€” TripNest makes the entire journey effortless.
        </p>
      </motion.div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
        {steps.map((step, i) => (
          <motion.div
            key={step.n}
            initial={{ opacity: 0, y: 28 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: i * 0.1 }}
            className="relative"
          >
            {i < steps.length - 1 && (
              <div className="hidden lg:block absolute top-8 left-full w-full h-px bg-gradient-to-r from-gray-200 dark:from-gray-700 to-transparent -translate-x-4 z-0" />
            )}
            <div className="relative z-10">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                transition={{ duration: 0.2 }}
                className="w-16 h-16 rounded-2xl flex items-center justify-center mb-5 shadow-lg"
                style={{ background: 'linear-gradient(135deg, #1e3a5f 0%, #0f2035 100%)' }}
              >
                <span className="text-white font-bold text-xl font-display">{step.n}</span>
              </motion.div>
              <h3 className="font-bold text-gray-900 dark:text-white text-lg mb-2">{step.title}</h3>
              <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed">{step.desc}</p>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  </section>
);

// â”€â”€â”€ Footer â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const Footer: React.FC = () => (
  <footer className="bg-[#060e1a] text-white py-16">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-10 mb-12">
        <div>
          <div className="flex items-center gap-2 mb-4">
            <div className="w-8 h-8 bg-[#1e3a5f] rounded-lg flex items-center justify-center">
              <Globe className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold font-display">TripNest</span>
          </div>
          <p className="text-white/50 text-sm leading-relaxed">
            AI-powered travel planning for solo adventurers, families, and groups.
          </p>
        </div>
        {[
          { title: 'Product',  links: ['Features', 'Changelog', 'Roadmap'] },
          { title: 'Company',  links: ['About', 'Blog', 'Careers', 'Press'] },
          { title: 'Legal',    links: ['Privacy', 'Terms', 'Cookie Policy', 'Licenses'] },
        ].map(col => (
          <div key={col.title}>
            <h4 className="font-bold text-xs uppercase tracking-widest text-white/40 mb-4">{col.title}</h4>
            <ul className="space-y-2">
              {col.links.map(link => (
                <li key={link}>
                  <span className="text-white/55 text-sm hover:text-white transition-colors cursor-pointer">{link}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className="border-t border-white/10 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
        <p className="text-white/40 text-sm">Â© 2025 TripNest. All rights reserved.</p>
        <p className="text-white/40 text-sm">Built with â¤ï¸ for travelers everywhere</p>
      </div>
    </div>
  </footer>
);

// â”€â”€â”€ Main â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const HomePage: React.FC = () => (
  <div className="dark:bg-[#060e1a]">
    <Hero />
    <FeaturesSection />
    <DestinationsSection />
    <HowItWorks />
    <Footer />
  </div>
);

export default HomePage;
